import { styled } from "../../stitches.config";
import React, { ReactElement, useEffect, useState } from "react";
import Head from "next/head";

export default function Layout({ children }: { children: ReactElement }) {
    return (
        <>
            <Head>
                <title>Tie-dye</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>{children}</main>
        </>
    )
}
